CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(60) NOT NULL UNIQUE,
    nome VARCHAR(120) NOT NULL,
    senha VARCHAR(120) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60)
);

CREATE INDEX idx_usuario_perfil ON usuario(perfil);
