CREATE TABLE disciplina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60)
);

CREATE TABLE turma (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    periodo VARCHAR(30) NOT NULL,
    disciplina_id BIGINT NOT NULL REFERENCES disciplina(id),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60)
);

CREATE TABLE vinculo_professor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT NOT NULL REFERENCES usuario(id),
    turma_id BIGINT NOT NULL REFERENCES turma(id),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_vinculo_professor_turma UNIQUE (professor_id, turma_id)
);

CREATE TABLE matricula_aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL REFERENCES usuario(id),
    turma_id BIGINT NOT NULL REFERENCES turma(id),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_matricula_aluno_turma UNIQUE (aluno_id, turma_id)
);

CREATE INDEX idx_turma_disciplina ON turma(disciplina_id);
CREATE INDEX idx_vinculo_professor ON vinculo_professor(professor_id);
CREATE INDEX idx_matricula_aluno ON matricula_aluno(aluno_id);
