CREATE TABLE trilha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(160) NOT NULL,
    descricao VARCHAR(1000),
    status VARCHAR(20) NOT NULL,
    disciplina_id BIGINT NOT NULL REFERENCES disciplina(id),
    professor_id BIGINT NOT NULL REFERENCES usuario(id),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60)
);

CREATE TABLE modulo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trilha_id BIGINT NOT NULL REFERENCES trilha(id) ON DELETE CASCADE,
    titulo VARCHAR(160) NOT NULL,
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_modulo_ordem UNIQUE (trilha_id, ordem)
);

CREATE TABLE licao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo_id BIGINT NOT NULL REFERENCES modulo(id) ON DELETE CASCADE,
    titulo VARCHAR(160) NOT NULL,
    resumo VARCHAR(1000),
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_licao_ordem UNIQUE (modulo_id, ordem)
);

CREATE TABLE desafio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licao_id BIGINT NOT NULL REFERENCES licao(id) ON DELETE CASCADE,
    enunciado VARCHAR(2000) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    dificuldade VARCHAR(20) NOT NULL,
    explicacao VARCHAR(2000) NOT NULL,
    ordem INTEGER NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_desafio_ordem UNIQUE (licao_id, ordem)
);

CREATE TABLE opcao_desafio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desafio_id BIGINT NOT NULL REFERENCES desafio(id) ON DELETE CASCADE,
    texto VARCHAR(1000) NOT NULL,
    ordem INTEGER NOT NULL,
    correta BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_opcao_ordem UNIQUE (desafio_id, ordem)
);

CREATE INDEX idx_trilha_professor ON trilha(professor_id);
CREATE INDEX idx_trilha_disciplina ON trilha(disciplina_id);
