CREATE TABLE trilha_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trilha_id BIGINT NOT NULL REFERENCES trilha(id),
    numero_versao INTEGER NOT NULL,
    titulo VARCHAR(160) NOT NULL,
    descricao VARCHAR(1000),
    disciplina_id BIGINT NOT NULL REFERENCES disciplina(id),
    professor_id BIGINT NOT NULL REFERENCES usuario(id),
    publicada_em TIMESTAMP NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_trilha_numero_versao UNIQUE (trilha_id, numero_versao)
);

CREATE TABLE modulo_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trilha_versao_id BIGINT NOT NULL REFERENCES trilha_versao(id) ON DELETE CASCADE,
    titulo VARCHAR(160) NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT uk_modulo_versao_ordem UNIQUE (trilha_versao_id, ordem)
);

CREATE TABLE licao_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo_versao_id BIGINT NOT NULL REFERENCES modulo_versao(id) ON DELETE CASCADE,
    titulo VARCHAR(160) NOT NULL,
    resumo VARCHAR(1000),
    ordem INTEGER NOT NULL,
    CONSTRAINT uk_licao_versao_ordem UNIQUE (modulo_versao_id, ordem)
);

CREATE TABLE desafio_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    licao_versao_id BIGINT NOT NULL REFERENCES licao_versao(id) ON DELETE CASCADE,
    enunciado VARCHAR(2000) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    dificuldade VARCHAR(20) NOT NULL,
    explicacao VARCHAR(2000) NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT uk_desafio_versao_ordem UNIQUE (licao_versao_id, ordem)
);

CREATE TABLE opcao_desafio_versao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desafio_versao_id BIGINT NOT NULL REFERENCES desafio_versao(id) ON DELETE CASCADE,
    texto VARCHAR(1000) NOT NULL,
    ordem INTEGER NOT NULL,
    correta BOOLEAN NOT NULL,
    CONSTRAINT uk_opcao_versao_ordem UNIQUE (desafio_versao_id, ordem)
);

CREATE INDEX idx_trilha_versao_trilha ON trilha_versao(trilha_id);
