CREATE TABLE distribuicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    versao_id BIGINT NOT NULL REFERENCES trilha_versao(id),
    turma_id BIGINT NOT NULL REFERENCES turma(id),
    disponivel_de TIMESTAMP NOT NULL,
    disponivel_ate TIMESTAMP,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_distribuicao_versao_turma UNIQUE (versao_id, turma_id)
);

CREATE INDEX idx_distribuicao_turma ON distribuicao(turma_id);
