CREATE TABLE sessao_aprendizagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distribuicao_id BIGINT NOT NULL REFERENCES distribuicao(id),
    aluno_id BIGINT NOT NULL REFERENCES usuario(id),
    desafio_atual_id BIGINT REFERENCES desafio_versao(id),
    status VARCHAR(20) NOT NULL,
    concluida_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60),
    CONSTRAINT uk_sessao_distribuicao_aluno UNIQUE (distribuicao_id, aluno_id)
);

CREATE TABLE tentativa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL REFERENCES sessao_aprendizagem(id),
    desafio_id BIGINT NOT NULL REFERENCES desafio_versao(id),
    opcao_id BIGINT NOT NULL REFERENCES opcao_desafio_versao(id),
    correta BOOLEAN NOT NULL,
    respondida_em TIMESTAMP NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    criado_por VARCHAR(60),
    atualizado_por VARCHAR(60)
);

CREATE INDEX idx_sessao_aluno ON sessao_aprendizagem(aluno_id);
CREATE INDEX idx_tentativa_sessao ON tentativa(sessao_id);
CREATE INDEX idx_tentativa_desafio ON tentativa(desafio_id);
